### PR TITLE
Build overline2

### PR DESCRIPTION
**Pull request by Robinlovelace**
This shows the approach for #81 and https://github.com/npct/pct-shiny/issues/703. Happy for this to be merged @AnnaGoodman1 ? Can tidy-up on master branch if so (it's not quite finished but is reproducible with the latest github version of stplanr).

### CODE REVIEW

**Comment by AnnaGoodman1** [comment]
In /build_params_pct_region.csv, could you save the new value to 'mingodutch_rnet' column? Also is it 'at least 150 commuters or 'more than 150'?

**Comment by Robinlovelace** [comment]
Hi @AnnaGoodman1 I've changed the variable name as requested - matter of preference but happy to go with your preferences on this. Yes it's `dutch >= min` as in the code in this PR.

``` r
u_params = "https://github.com/npct/pct-scripts/raw/755ff49728409b598e69b95570885631c3e109f0/commute/lsoa/build_params_pct_region.csv"
build_params_new = build_params_old = readr::read_csv(u_params)
#> Parsed with column specification:
#> cols(
#>   region_name = col_character(),
#>   minflow_visualise = col_double(),
#>   minflow_rnet = col_double(),
#>   rnet_keep = col_double(),
#>   to_rebuild = col_double(),
#>   to_rebuild_rnet = col_double(),
#>   n_flow = col_double(),
#>   n_people = col_double(),
#>   n_flow_rnet = col_logical(),
#>   n_people_rnet = col_logical(),
#>   build_date = col_date(format = ""),
#>   run_min = col_double(),
#>   minflow_rnet_lsoa = col_double()
#> )
build_params_new$mingodutch_rnet = build_params_old$minflow_rnet_lsoa
build_params_new$minflow_rnet_lsoa = NULL
readr::write_csv(build_params_new, "~/h/npct/pct-scripts/commute/lsoa/build_params_pct_region.csv")
```

<sup>Created on 2019-04-09 by the [reprex package](https://reprex.tidyverse.org) (v0.2.1)</sup>

I think it would be good to add more columns to this build log, but this should do for now. Anything else you'd like changing, let me know (and feel free to update column names as you see fit, happy to defer to your judgement on names)!

**Comment by AnnaGoodman1** [comment]
ok great, I guess only thing is should the 0 be 1? I.e. 'at least 1 commuter in Go Dutch'? Or does it also include routes with 0 in go dutch but 1 in ebike?

**Comment by Robinlovelace** [comment]
It also includes routes with 0 in Go Dutch, yes. For the majority of regions no subsetting is needed.

**Pull request merged**
