### PR TITLE
Split out model output from build

### PR DESCRIPTION
**Pull request by nikolai-b**
@RachelAldred when this goes in you can access the variables in the `model_output.Rmd` file.

@Robinlovelace I tested this but would be good if you could also build a region.

### CODE REVIEW

**Comment by Robinlovelace** [comment]
Yes built kent - works. Moved the `source(build_region)` bit into buildmaster.R, commented out the bit that creates `model-output.html`, to be uncommented when this is fixed.

**Comment by RachelAldred** [comment]
Hi @Robinlovelace @nikolai-b Does this mean - just checking before I mess around with it! - that all those variables are now defined 1st somewhere else, so they don't need to be defined in the Model Output.RMD and I can just refer to them there? Also, quick query, is there a way I can calculate (and include in the Model Output tab) what % of flows in the region in question are between or within zones? Thanks!

**Comment by Robinlovelace** [comment]
Yes that's easy to do @RachelAldred . If you just say in the text XX% of flows were intrazone, @nikolai-b and I will figure out what you mean and add the appropriate code, e.g. `r sum(l$All[l$dist == 0]) / sum(l$All)`. Thanks for keeping the ball rolling on this.

**Comment by RachelAldred** [comment]
Thanks! Have made a start on this, hopefully you got sent it.

**Pull request merged**
